CREATE DATABASE DEMO;
USE DEMO;
CREATE TABLE CUSTOMERS(
customer_id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50)NOT NULL,
last_name VARCHAR(50)NOT NULL,
email VARCHAR(100)UNIQUE,
phone_number VARCHAR(15),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP DATABASE DEMO;